name: robopy
channels:
 - conda-forge
dependencies:
  - mesalib>=17
  - vtk>=7
  - ipyvolume==0.5.1
  - ipywidgets>=7.4.0
  - ipywebrtc>=0.4
  - pip:
      - matplotlib
      - Pillow
      - scipy
      - numpy
      - requests
      - scikit-image>=0.13
  - notebook>=5.3
