name: robopy
channels:
  - conda-forge
dependencies:
  - 'vtk[version>=7 build=py36_mesalib*]'
  - ipyvolume==0.5.1
  - ipywidgets>=7.4.0
  - ipywebrtc>=0.4
  - pip:
      - matplotlib>=3
      - Pillow
      - scipy
      - numpy
      - requests
      - scikit-image>=0.13
  - notebook>=5.3
