name: robopy-ipynb
channels:
  - conda-forge
dependencies:
  - python=3.6
  - vtk==8.1.1=py36_mesalibhed38e9a_4
  - mesalib=>17
  - ipyvolume==0.5.1
  - ipywidgets>=7.4.0
  - ipywebrtc>=0.4
  - pip:
      - matplotlib>=3
      - Pillow
      - scipy
      - numpy
      - requests
      - scikit-image>=0.13
  - notebook>=5.3
