name: robopy
channels:
  - conda-forge
dependencies:
  - mesalib>=17.3.9
  - vtk>=8.1.1
  - ipyvolume==0.5.1
  - ipywidgets>=7.4.0
  - ipywebrtc>=0.4
  - pip:
      - matplotlib>=3
      - Pillow
      - scipy
      - numpy
      - requests
      - scikit-image>=0.13
  - notebook>=5.3
